### ISSUE TITLE
Incorrect number of available objects when Manager::create returns an error

### ISSUE THREAD

**Issue by alexwl** [bikeshedder/deadpool#18] opened 2019-12-15 14:56 UTC
Hi!

I was experimenting with this library and found a problem with how the number of available objects in the pool is calculated.

Example:

```rust
use async_trait::async_trait;
use deadpool::*;
use futures::channel::oneshot;

#[derive(Debug)]
struct Manager {
    should_fail: bool,
}

#[derive(Debug)]
enum Error {
    Fail,
}

#[derive(Debug)]
struct Connection;

#[async_trait]
impl deadpool::Manager<Connection, Error> for Manager {
    async fn create(&self) -> Result<Connection, Error> {
        if self.should_fail {
            Err(Error::Fail)
        } else {
            Ok(Connection)
        }
    }
    async fn recycle(&self, _conn: &mut Connection) -> Result<(), Error> {
        Ok(())
    }
}

#[tokio::main]
async fn main() -> Result<(), Error> {
    let manager = Manager { should_fail: true }; // when should_fail: false this program doesn't hang
    let pool = Pool::new(manager, 10);
    let pool_clone = pool.clone();
    let (tx, rx) = oneshot::channel::<()>();
    let join_handle_1 = tokio::spawn(async move {
        println!("1: {:?}", pool_clone.status());
        let _conn = pool_clone.get().await;
        tx.send(()).unwrap();
    });
    let pool_clone = pool.clone();
    let join_handle_2 = tokio::spawn(async move {
        rx.await.unwrap();
        println!("2: {:?}", pool_clone.status());
        let _conn = pool_clone.get().await;
    });
    let _ = join_handle_1.await;
    let _ = join_handle_2.await;
    Ok(())
}
```

This program prints

```
1: Status { size: 0, available: 0 }
2: Status { size: 0, available: 1 }
```

and hangs.

My understanding is that after the first call to `get` the value of `available` is 1 because the `obj` is dropped when `obj.state` == `ObjectState::Creating`:
https://github.com/bikeshedder/deadpool/blob/cadbf707da7b668333224ed2cd310f164a5fdabb/src/lib.rs#L111-L114

The second call to `get` hangs on `recv` because `available` > 0

**Comment by bikeshedder** [comment] 2019-12-15 15:13
I have way too much time making this part as robust as possible without introducing the need for an executor or mutexes. Swapping those two lines should eliminate the deadlock but there are still other issues with using two atomics for synchronization.

When `max_size+n` futures try to get an object from the pool and all creations fail there will be `n` futures waiting for an object to be returned to the pool for all eternity.

**Comment by bikeshedder** [comment] 2019-12-15 15:14
Whops. I did not mean to close this issue. (Pressed that button by accident)

I need to prepare test cases for that corner cases and find another way to return objects to the pool that is 100% bullet proof.

**Comment by bikeshedder** [comment] 2019-12-15 15:40
Oh my... I just see what the problem is. `available` is already increased by one before calling `Manager.create`. When create fails only the size needs to bw reduced by one.

It got nothing to do with the possible race condition that I described earlier.

**Comment by alexwl** [comment] 2019-12-15 15:59
Thanks for quick response!

Commenting out the line
https://github.com/bikeshedder/deadpool/blob/cadbf707da7b668333224ed2cd310f164a5fdabb/src/lib.rs#L112
fixes this particular problem.

The program prints
```
1: Status { size: 0, available: 0 }
2: Status { size: 0, available: 0 }
```
and exits.


But I'm not sure if it is the correct solution. Tests are definitely needed.

**Closed** 2019-12-15 18:20 UTC
