### ISSUE TITLE
Add support for odbc

### ISSUE THREAD

**Issue by bbigras** [bikeshedder/deadpool#43] opened 2020-02-19 19:40 UTC
I have a noob question.

I would like to do something like:

```rust
use async_std::sync::{Arc, Mutex};
use async_trait::async_trait;
use failure::Error;
use odbc_safe::AutocommitOn;

use std::env;

struct Conn {
    conn: Mutex<Arc<odbc::Connection<'static, AutocommitOn>>>,
}
struct Manager {}
type Pool = deadpool::managed::Pool<Conn, Error>;

#[async_trait]
impl deadpool::managed::Manager<Conn, Error> for Manager {
    async fn create(&self) -> Result<Conn, Error> {
        let env = odbc::create_environment_v3_with_os_db_encoding("utf-8", "latin1").unwrap();

        let conn_str = env::var("SQL_STR").unwrap();

        let conn = env.connect_with_connection_string(&conn_str).unwrap();

        let conn = Mutex::new(Arc::new(conn));

        Ok(Conn { conn })
    }

    async fn recycle(&self, conn: &mut Conn) -> deadpool::managed::RecycleResult<Error> {
        Ok(())
    }
}
```

but the compiler complains that `'*mut odbc_sys::Env' cannot be shared between threads safely`.

Why isn't the Mutex and Arc enough for this?

**Comment by bikeshedder** [comment] 2020-02-19 20:56
It should be the other way around: `Arc<Mutex<...>>`

**Comment by bbigras** [comment] 2020-02-19 21:06
Thanks for the quick reply, I have the same problem.

I forgot to paste the log in my last post:

```
error[E0277]: `*mut odbc_sys::Dbc` cannot be sent between threads safely
  --> src/pool.rs:28:89
   |
28 |       async fn recycle(&self, conn: &mut Conn) -> deadpool::managed::RecycleResult<Error> {
   |  _________________________________________________________________________________________^
29 | |         Ok(())
30 | |     }
   | |_____^ `*mut odbc_sys::Dbc` cannot be sent between threads safely
   |
   = help: within `odbc::connection::Connection<'static, odbc_safe::data_source::connected::AutocommitOn>`, the trait `std::marker::Send` is not implemented for `*mut odbc_sys::Dbc`
   = note: required because it appears within the type `odbc_safe::handles::hdbc::HDbc<'_>`
   = note: required because it appears within the type `odbc_safe::data_source::connected::Connected<'_, odbc_safe::data_source::connected::AutocommitOn>`
   = note: required because it appears within the type `odbc_safe::data_source::DataSource<'static, odbc_safe::data_source::connected::Connected<'static, odbc_safe::data_source::connected::AutocommitOn>>`
   = note: required because it appears within the type `odbc::connection::Connection<'static, odbc_safe::data_source::connected::AutocommitOn>`
   = note: required because of the requirements on the impl of `std::marker::Send` for `async_std::sync::mutex::Mutex<odbc::connection::Connection<'static, odbc_safe::data_source::connected::AutocommitOn>>`
   = note: required because of the requirements on the impl of `std::marker::Send` for `std::sync::Arc<async_std::sync::mutex::Mutex<odbc::connection::Connection<'static, odbc_safe::data_source::connected::AutocommitOn>>>`
   = note: required because it appears within the type `pool::Conn`
   = note: required because of the requirements on the impl of `std::marker::Send` for `&mut pool::Conn`
   = note: required because it appears within the type `[static generator@src/pool.rs:28:89: 30:6 _self:&pool::Manager, conn:&mut pool::Conn {}]`
   = note: required because it appears within the type `std::future::GenFuture<[static generator@src/pool.rs:28:89: 30:6 _self:&pool::Manager, conn:&mut pool::Conn {}]>`
   = note: required because it appears within the type `impl core::future::future::Future`
   = note: required because it appears within the type `impl core::future::future::Future`
   = note: required for the cast to the object type `dyn core::future::future::Future<Output = std::result::Result<(), deadpool::managed::errors::RecycleError<failure::error::Error>>> + std::marker::Send`


error[E0277]: `*mut odbc_sys::Env` cannot be shared between threads safely
  --> src/pool.rs:28:89
   |
28 |       async fn recycle(&self, conn: &mut Conn) -> deadpool::managed::RecycleResult<Error> {
   |  _________________________________________________________________________________________^
29 | |         Ok(())
30 | |     }
   | |_____^ `*mut odbc_sys::Env` cannot be shared between threads safely
   |
   = help: within `odbc_safe::handles::henv::HEnv`, the trait `std::marker::Sync` is not implemented for `*mut odbc_sys::Env`
   = note: required because it appears within the type `odbc_safe::handles::henv::HEnv`
   = note: required because of the requirements on the impl of `std::marker::Send` for `&odbc_safe::handles::henv::HEnv`
   = note: required because it appears within the type `std::marker::PhantomData<&odbc_safe::handles::henv::HEnv>`
   = note: required because it appears within the type `odbc_safe::handles::hdbc::HDbc<'_>`
   = note: required because it appears within the type `odbc_safe::data_source::connected::Connected<'_, odbc_safe::data_source::connected::AutocommitOn>`
   = note: required because it appears within the type `odbc_safe::data_source::DataSource<'static, odbc_safe::data_source::connected::Connected<'static, odbc_safe::data_source::connected::AutocommitOn>>`
   = note: required because it appears within the type `odbc::connection::Connection<'static, odbc_safe::data_source::connected::AutocommitOn>`
   = note: required because of the requirements on the impl of `std::marker::Send` for `async_std::sync::mutex::Mutex<odbc::connection::Connection<'static, odbc_safe::data_source::connected::AutocommitOn>>`
   = note: required because of the requirements on the impl of `std::marker::Send` for `std::sync::Arc<async_std::sync::mutex::Mutex<odbc::connection::Connection<'static, odbc_safe::data_source::connected::AutocommitOn>>>`
   = note: required because it appears within the type `pool::Conn`
   = note: required because of the requirements on the impl of `std::marker::Send` for `&mut pool::Conn`
   = note: required because it appears within the type `[static generator@src/pool.rs:28:89: 30:6 _self:&pool::Manager, conn:&mut pool::Conn {}]`
   = note: required because it appears within the type `std::future::GenFuture<[static generator@src/pool.rs:28:89: 30:6 _self:&pool::Manager, conn:&mut pool::Conn {}]>`
   = note: required because it appears within the type `impl core::future::future::Future`
   = note: required because it appears within the type `impl core::future::future::Future`
   = note: required for the cast to the object type `dyn core::future::future::Future<Output = std::result::Result<(), deadpool::managed::errors::RecycleError<failure::error::Error>>> + std::marker::Send`
```

**Comment by bikeshedder** [comment] 2020-02-21 12:14
It seams the `odbc` crate does not provide a thread-safe way of using the connection object. In order to solve that you could spawn the client in its own thread and use some kind of IPC (e.g. a `tokio::sync::mpsc::channel`) to communicate between your code and the database client object.

I would recommend asking the author(s) of the `odbc` crate and ask if this is by design and if there is a solution for that.

**Comment by bikeshedder** [comment] 2020-02-28 16:11
I'm marking this as a new feature which is blocked by https://github.com/Koka/odbc-rs/issues/131 for now.

**Comment by bikeshedder** [comment] 2024-06-18 21:40
As there has been no progress on Koka/odbc-rs#131 for quite some time now and the crate seams pretty dead I'm going to close this issue for the time being.

If anyone needs this and implements a communication channel as described in https://github.com/bikeshedder/deadpool/issues/43#issuecomment-589628869 or fixes this some other way I'd welcome a PR for adding `deadpool-odbc`.

**Closed by bikeshedder** 2024-06-18 21:40 UTC
Labels: enhancement, S-blocked, A-odbc

**Comment by bbigras** [comment] 2024-06-19 01:09
odbc-rs is abandoned. 

odbc-api is still active.
