### ISSUE TITLE
Connection not returned when dropped in `deadpool_redis`

### ISSUE THREAD

**Issue by Yohe-Am** [bikeshedder/deadpool#130] opened 2021-08-26 11:04 UTC
I'm using blocking redis commands inside async infinite loops which get dropped after a certain timeout. Problem is, after the timeout, the pool blocks forever to get back the connection. Middle of a very busy week so I've not investigated this well but I've tried using the standard redis client and this issue disappears. (comment that back in to give it a try)

```rust

#[actix_rt::test]
async fn redis_test() {
    let pool = deadpool_redis::Config {
        url: Some("redis://localhost".to_string()),
        connection: None,
        ..Default::default()
    }
    .create_pool()
    .unwrap();
    // let pool = redis::Client::open("redis://localhost".to_string()).unwrap();

    let stream_key = "test_stream";
    let group = "test_group";
    let consumer = "test_consumer";
    {
        let mut conn = pool.get().await.expect("conn");
        // let mut conn = pool.get_async_connection().await.expect("conn");

        // del anything under the key in case previous test didn't clean up properly
        redis::Cmd::del(&stream_key[..])
            .query_async::<_, ()>(&mut conn)
            .await
            .unwrap();

        // create consumer group
        redis::Cmd::xgroup_create_mkstream(&stream_key[..], &group[..], &["0"])
            .query_async::<_, ()>(&mut conn)
            .await
            .unwrap();

        println!("created group");
    }
    {
        let mut conn = pool.get().await.expect("conn");
        // let mut conn = pool.get_async_connection().await.expect("conn");

        // add message to stream
        redis::Cmd::xadd(
            &stream_key[..],
            "*",
            &[("stuff", "stuffer")][..], 
        )
        .query_async::<_, ()>(&mut conn)
        .await
        .unwrap();

        println!("added message");
    }
    {
        let mut conn = pool.get().await.expect("conn");
        // let mut conn = pool.get_async_connection().await.expect("conn");

        // async inf loop with timeout
        let _ = tokio::time::timeout(std::time::Duration::from_millis(500), async move {
            // start from the begenning
            let mut id = "0";
            loop {
                let items = redis::Cmd::xread_options(
                    &[&stream_key[..]],
                    &[&id[..]],
                    redis::streams::StreamReadOptions::default()
                        .block(0)
                        .count(10)
                        .group(&group[..], &consumer[..]),
                )
                .query_async::<_, redis::streams::StreamReadReply>(&mut conn)
                .await
                .unwrap();

                let mut ctr = 0;
                for redis::streams::StreamKey { ids, .. } in items.keys {
                    for redis::streams::StreamId { id: msg_id, .. } in ids {
                        redis::Cmd::xack(&stream_key[..], &group[..], &[msg_id])
                            .query_async::<_, ()>(&mut conn)
                            .await
                            .unwrap();
                        ctr += 1;
                    }
                }
                // if no items are returned, this means we've read everything availiable
                // block for new items now
                if ctr == 0 {
                    id = ">";
                }
            }
        })
        .await
        .unwrap();

        println!("ended loop");
    }
    {
        let mut conn = pool.get().await.expect("conn");
        // let mut conn = pool.get_async_connection().await.expect("conn");

        println!("got connection");

        let stream_msgs = redis::Cmd::xread_options(
            &[&stream_key[..]],
            &[">"],
            redis::streams::StreamReadOptions::default()
                .count(1)
                .group(&group[..], &consumer[..]),
        )
        .query_async::<_, redis::streams::StreamReadReply>(&mut conn)
        .await
        .unwrap();

        // tracing::info!("got here: {:?}", stream_msgs);
        let stream_msgs = &stream_msgs.keys;
        // let stream_msgs = &stream_msgs.keys[0].ids;
        assert!(stream_msgs.is_empty());
        println!("checked for items");
    }
}

```

**Comment by bikeshedder** [comment] 2021-09-10 12:41
I just gave your testcase a try: https://github.com/bikeshedder/deadpool/tree/issue/130

After looking into it I found that the object is in fact returned to the pool. It hangs when trying to recycle the connection. The stream query is still running and therefore the `ping` command reads the response from the previous stream command which never comes. This is another issue caused by mitsuhiko/redis-rs#325 and needs to be fixed in the `redis` crate.

The only workaround for this would be to wrap `execute_async` and mark the connection as unrecoverable if the future returned by `execute_saync` is not polled to completion. This should best be added to the redis crate directly though. If redis doesn't support aborting commands at least the connection should be marked as broken when someone tries do to that.

In the mean time you can specify a `recycle timeout` so it doesn't block your application forever. It's not a perfect solution but the connection will at least only be tried once and then dropped for good after the recycle timeout has elapsed.

**Comment by bikeshedder** [comment] 2021-09-10 12:43
I'm closing this issue as it's definitely a `redis` issue.

The object is returned to the pool and by using a recycle timeout you can work around this problem.

Specifying timeouts for any kind of external service is a good idea anyways.

**Closed by bikeshedder** 2021-09-10 12:43 UTC
Labels: question, A-redis
